spring:
  application:
    name: GestPro

  datasource:
    url: jdbc:postgresql://localhost:5432/GestProDb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
      hibernate:
        show_sql: true

  flyway:
    enabled: true

  # Management server configuration
  # Change information in the production environment
  rabbitmq:
    host: localhost
    port: 5672 #  porta AMQP
    username: admin
    password: admin

logging:
  level:
    org.springframework.security: DEBUG
